# GET http://localhost:5000/user
# Content-Type: application/x-www-form-urlencoded
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRlNGUzNzIwMjZjOWQxYWQzNzQzY2U3IiwidXNlcl9uYW1lIjoiTXVoYW1tYWQgUml6a3kgRmlybWFuc3lhaCIsInVzZXJfZW1haWwiOiJyaXp1a2lmaXJ1bWFuc2hhYTk2QGdtYWlsLmNvbSIsInVzZXJfZ2VuZGVyIjoiMDg1Mzk1ODE0MDc2IiwidXNlcl9wZXJtaXNzaW9uIjoiVXNlciIsImlhdCI6MTU3NTQ0NTcxNSwiZXhwIjoxNTc1NTMyMTE1fQ.3APizDV_xjpPaYjHZ__CaHNKDxdLdvyfLH1VzGXX6cg

# POST http://localhost:5000/user
# Content-Type: application/x-www-form-urlencoded
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRlNGUzNzIwMjZjOWQxYWQzNzQzY2U3IiwidXNlcl9uYW1lIjoiTXVoYW1tYWQgUml6a3kgRmlybWFuc3lhaCIsInVzZXJfZW1haWwiOiJyaXp1a2lmaXJ1bWFuc2hhYTk2QGdtYWlsLmNvbSIsInVzZXJfZ2VuZGVyIjoiMDg1Mzk1ODE0MDc2IiwidXNlcl9wZXJtaXNzaW9uIjoiVXNlciIsImlhdCI6MTU3NTQ0NTcxNSwiZXhwIjoxNTc1NTMyMTE1fQ.3APizDV_xjpPaYjHZ__CaHNKDxdLdvyfLH1VzGXX6cg

# name=aaa
# &email=rizukifirumanshaa96@gmail.com
# &password=admin123
# &username=rrra
# &phone=997
# &gender=male
# role_id=Admin

# DELETE http://localhost:5000/user/5de4e372026c9d1ad3743ce7
# Content-Type: application/x-www-form-urlencoded
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRlNGUzNzIwMjZjOWQxYWQzNzQzY2U3IiwidXNlcl9uYW1lIjoiTXVoYW1tYWQgUml6a3kgRmlybWFuc3lhaCIsInVzZXJfZW1haWwiOiJyaXp1a2lmaXJ1bWFuc2hhYTk2QGdtYWlsLmNvbSIsInVzZXJfZ2VuZGVyIjoiMDg1Mzk1ODE0MDc2IiwidXNlcl9wZXJtaXNzaW9uIjoiVXNlciIsImlhdCI6MTU3NTQ0NTcxNSwiZXhwIjoxNTc1NTMyMTE1fQ.3APizDV_xjpPaYjHZ__CaHNKDxdLdvyfLH1VzGXX6cg

GET http://localhost:5000/role
Content-Type: application/x-www-form-urlencoded
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRlNGUzNzIwMjZjOWQxYWQzNzQzY2U3IiwidXNlcl9uYW1lIjoiTXVoYW1tYWQgUml6a3kgRmlybWFuc3lhaCIsInVzZXJfZW1haWwiOiJyaXp1a2lmaXJ1bWFuc2hhYTk2QGdtYWlsLmNvbSIsInVzZXJfZ2VuZGVyIjoiMDg1Mzk1ODE0MDc2IiwidXNlcl9wZXJtaXNzaW9uIjoiVXNlciIsImlhdCI6MTU3NTQ0NTcxNSwiZXhwIjoxNTc1NTMyMTE1fQ.3APizDV_xjpPaYjHZ__CaHNKDxdLdvyfLH1VzGXX6cg